# Site settings
author: Philip Lee-Chin
title: The Journey
header-img: img/home-bg.png
email: phil.leechin@outlook.com
copyright_name: Philip Lee-Chin
description: > # this means to ignore newlines until "baseurl:"
  Climbing the mountain of codes
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  PhilLeeChin

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
